name: CI

on:
  pull_request:
    types: [opened]
    branches:
      - challenge
      
jobs:
  getflag:
    runs-on:
      labels: self-hosted

    steps:
      - name: fuc_name
        run: echo "fuc u"
        id: fuc_id
